---
abstract: 'get the full path to a locally installed module'
author:
  - 'Neil Bowers <neil@bowers.com>'
build_requires:
  Devel::FindPerl: 0
  File::Spec::Functions: 0
  FindBin: 0.05
  Test::More: 0.88
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.013, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Module-Path
requires:
  Cwd: 0
  Exporter: 0
  File::Basename: 0
  Getopt::Long: 0
  Pod::Usage: 0
  perl: 5.006
  strict: 0
  warnings: 0
resources:
  homepage: https://github.com/neilbowers/Module-Path
  repository: https://github.com/neilbowers/Module-Path.git
version: 0.12
