---
abstract: 'get the full path to a locally installed module'
author:
  - 'Neil Bowers <neil@bowers.com>'
build_requires:
  Test::More: 0.88
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300021, CPAN::Meta::Converter version 2.120630'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Module-Path
requires:
  Exporter: 0
  strict: 0
  warnings: 0
resources:
  repository: git://github.com/neilbowers/https://github.com/neilbowers/Module-Path.git
version: 0.02
